apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingapp
  labels:
    app: pingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingapp
  template:
    metadata:
      labels:
        app: pingapp
    spec:
      containers:
      - name: pingapp
        image: nicopaez/pingapp:2.1.0
        ports:
        - containerPort: 4567
        envFrom:
          - configMapRef:
              name: pingapp-config-1
        volumeMounts:
          - name: config-files
            mountPath: /mydata
          - name: config-secrets
            mountPath: /mysecrets
      volumes:
        - name: config-files
          configMap:
            name: "pingapp-config-2"
            items:
            - key: "config.json"
              path: "config.json"
        - name: config-secrets
          secret:
            secretName: "pingapp-secrets"
            items:
            - key: "secret.json"
              path: "secret.json"