version: '2'
services:
  web-1:
    image: nicopaez/password-api:2.1.0
    expose:
      - "3000"
  web-2:
    image: nicopaez/password-api:2.1.0
    expose:
      - "3000"
  nginx:
    image: nginx:1.23.1
    ports: 
      - "8080:8080"
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on: 
      - web-1
      - web-2
  